// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: pkg/api/grpc/proto/vector.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InsertRequest contains a vector and its metadata
type InsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`                                                                         // Namespace for multi-tenancy
	Vector        []float32              `protobuf:"fixed32,2,rep,packed,name=vector,proto3" json:"vector,omitempty"`                                                                      // Vector embedding
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Metadata key-value pairs
	Id            *string                `protobuf:"bytes,4,opt,name=id,proto3,oneof" json:"id,omitempty"`                                                                                 // Optional custom ID (auto-generated if not provided)
	Text          *string                `protobuf:"bytes,5,opt,name=text,proto3,oneof" json:"text,omitempty"`                                                                             // Optional text content for full-text search
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertRequest) Reset() {
	*x = InsertRequest{}
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRequest) ProtoMessage() {}

func (x *InsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRequest.ProtoReflect.Descriptor instead.
func (*InsertRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_proto_vector_proto_rawDescGZIP(), []int{0}
}

func (x *InsertRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *InsertRequest) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *InsertRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *InsertRequest) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *InsertRequest) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

// InsertResponse returns the ID of the inserted vector
type InsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`             // ID of inserted vector
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`  // Operation success status
	Error         *string                `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"` // Error message if failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertResponse) Reset() {
	*x = InsertResponse{}
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertResponse) ProtoMessage() {}

func (x *InsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertResponse.ProtoReflect.Descriptor instead.
func (*InsertResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_proto_vector_proto_rawDescGZIP(), []int{1}
}

func (x *InsertResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InsertResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InsertResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

// SearchRequest specifies vector search parameters
type SearchRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Namespace      string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`                                       // Namespace to search in
	QueryVector    []float32              `protobuf:"fixed32,2,rep,packed,name=query_vector,json=queryVector,proto3" json:"query_vector,omitempty"`       // Query vector
	K              int32                  `protobuf:"varint,3,opt,name=k,proto3" json:"k,omitempty"`                                                      // Number of results to return
	EfSearch       int32                  `protobuf:"varint,4,opt,name=ef_search,json=efSearch,proto3" json:"ef_search,omitempty"`                        // HNSW ef_search parameter (accuracy vs speed)
	Filter         *Filter                `protobuf:"bytes,5,opt,name=filter,proto3,oneof" json:"filter,omitempty"`                                       // Optional metadata filter
	DistanceMetric *string                `protobuf:"bytes,6,opt,name=distance_metric,json=distanceMetric,proto3,oneof" json:"distance_metric,omitempty"` // "cosine", "euclidean", or "dot_product"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_proto_vector_proto_rawDescGZIP(), []int{2}
}

func (x *SearchRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SearchRequest) GetQueryVector() []float32 {
	if x != nil {
		return x.QueryVector
	}
	return nil
}

func (x *SearchRequest) GetK() int32 {
	if x != nil {
		return x.K
	}
	return 0
}

func (x *SearchRequest) GetEfSearch() int32 {
	if x != nil {
		return x.EfSearch
	}
	return 0
}

func (x *SearchRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *SearchRequest) GetDistanceMetric() string {
	if x != nil && x.DistanceMetric != nil {
		return *x.DistanceMetric
	}
	return ""
}

// HybridSearchRequest combines vector and text search
type HybridSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`                                 // Namespace to search in
	QueryVector   []float32              `protobuf:"fixed32,2,rep,packed,name=query_vector,json=queryVector,proto3" json:"query_vector,omitempty"` // Query vector
	QueryText     string                 `protobuf:"bytes,3,opt,name=query_text,json=queryText,proto3" json:"query_text,omitempty"`                // Query text for full-text search
	K             int32                  `protobuf:"varint,4,opt,name=k,proto3" json:"k,omitempty"`                                                // Number of results to return
	EfSearch      int32                  `protobuf:"varint,5,opt,name=ef_search,json=efSearch,proto3" json:"ef_search,omitempty"`                  // HNSW ef_search parameter
	Filter        *Filter                `protobuf:"bytes,6,opt,name=filter,proto3,oneof" json:"filter,omitempty"`                                 // Optional metadata filter
	Config        *HybridSearchConfig    `protobuf:"bytes,7,opt,name=config,proto3,oneof" json:"config,omitempty"`                                 // Hybrid search configuration
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HybridSearchRequest) Reset() {
	*x = HybridSearchRequest{}
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HybridSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HybridSearchRequest) ProtoMessage() {}

func (x *HybridSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HybridSearchRequest.ProtoReflect.Descriptor instead.
func (*HybridSearchRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_proto_vector_proto_rawDescGZIP(), []int{3}
}

func (x *HybridSearchRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *HybridSearchRequest) GetQueryVector() []float32 {
	if x != nil {
		return x.QueryVector
	}
	return nil
}

func (x *HybridSearchRequest) GetQueryText() string {
	if x != nil {
		return x.QueryText
	}
	return ""
}

func (x *HybridSearchRequest) GetK() int32 {
	if x != nil {
		return x.K
	}
	return 0
}

func (x *HybridSearchRequest) GetEfSearch() int32 {
	if x != nil {
		return x.EfSearch
	}
	return 0
}

func (x *HybridSearchRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *HybridSearchRequest) GetConfig() *HybridSearchConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// HybridSearchConfig configures hybrid search fusion
type HybridSearchConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FusionMethod  string                 `protobuf:"bytes,1,opt,name=fusion_method,json=fusionMethod,proto3" json:"fusion_method,omitempty"`   // "rrf" or "weighted"
	VectorWeight  float32                `protobuf:"fixed32,2,opt,name=vector_weight,json=vectorWeight,proto3" json:"vector_weight,omitempty"` // Weight for vector results (alpha)
	TextWeight    float32                `protobuf:"fixed32,3,opt,name=text_weight,json=textWeight,proto3" json:"text_weight,omitempty"`       // Weight for text results (beta)
	RrfK          int32                  `protobuf:"varint,4,opt,name=rrf_k,json=rrfK,proto3" json:"rrf_k,omitempty"`                          // RRF k parameter (default 60)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HybridSearchConfig) Reset() {
	*x = HybridSearchConfig{}
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HybridSearchConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HybridSearchConfig) ProtoMessage() {}

func (x *HybridSearchConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HybridSearchConfig.ProtoReflect.Descriptor instead.
func (*HybridSearchConfig) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_proto_vector_proto_rawDescGZIP(), []int{4}
}

func (x *HybridSearchConfig) GetFusionMethod() string {
	if x != nil {
		return x.FusionMethod
	}
	return ""
}

func (x *HybridSearchConfig) GetVectorWeight() float32 {
	if x != nil {
		return x.VectorWeight
	}
	return 0
}

func (x *HybridSearchConfig) GetTextWeight() float32 {
	if x != nil {
		return x.TextWeight
	}
	return 0
}

func (x *HybridSearchConfig) GetRrfK() int32 {
	if x != nil {
		return x.RrfK
	}
	return 0
}

// SearchResponse returns search results
type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`                                   // List of results
	TotalResults  int32                  `protobuf:"varint,2,opt,name=total_results,json=totalResults,proto3" json:"total_results,omitempty"`    // Total number of results found
	SearchTimeMs  float32                `protobuf:"fixed32,3,opt,name=search_time_ms,json=searchTimeMs,proto3" json:"search_time_ms,omitempty"` // Search time in milliseconds
	Error         *string                `protobuf:"bytes,4,opt,name=error,proto3,oneof" json:"error,omitempty"`                                 // Error message if failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_proto_vector_proto_rawDescGZIP(), []int{5}
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchResponse) GetTotalResults() int32 {
	if x != nil {
		return x.TotalResults
	}
	return 0
}

func (x *SearchResponse) GetSearchTimeMs() float32 {
	if x != nil {
		return x.SearchTimeMs
	}
	return 0
}

func (x *SearchResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

// SearchResult represents a single search result
type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                       // Vector ID
	Distance      float32                `protobuf:"fixed32,2,opt,name=distance,proto3" json:"distance,omitempty"`                                                                         // Distance/similarity score
	Vector        []float32              `protobuf:"fixed32,3,rep,packed,name=vector,proto3" json:"vector,omitempty"`                                                                      // Original vector (optional)
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Metadata
	Text          *string                `protobuf:"bytes,5,opt,name=text,proto3,oneof" json:"text,omitempty"`                                                                             // Text content if available
	VectorScore   *float32               `protobuf:"fixed32,6,opt,name=vector_score,json=vectorScore,proto3,oneof" json:"vector_score,omitempty"`                                          // Individual vector similarity score
	TextScore     *float32               `protobuf:"fixed32,7,opt,name=text_score,json=textScore,proto3,oneof" json:"text_score,omitempty"`                                                // Individual text relevance score
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_proto_vector_proto_rawDescGZIP(), []int{6}
}

func (x *SearchResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SearchResult) GetDistance() float32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *SearchResult) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *SearchResult) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SearchResult) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

func (x *SearchResult) GetVectorScore() float32 {
	if x != nil && x.VectorScore != nil {
		return *x.VectorScore
	}
	return 0
}

func (x *SearchResult) GetTextScore() float32 {
	if x != nil && x.TextScore != nil {
		return *x.TextScore
	}
	return 0
}

// DeleteRequest specifies vector(s) to delete
type DeleteRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Namespace string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"` // Namespace
	// Types that are valid to be assigned to Selector:
	//
	//	*DeleteRequest_Id
	//	*DeleteRequest_Filter
	Selector      isDeleteRequest_Selector `protobuf_oneof:"selector"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_proto_vector_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DeleteRequest) GetSelector() isDeleteRequest_Selector {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *DeleteRequest) GetId() string {
	if x != nil {
		if x, ok := x.Selector.(*DeleteRequest_Id); ok {
			return x.Id
		}
	}
	return ""
}

func (x *DeleteRequest) GetFilter() *Filter {
	if x != nil {
		if x, ok := x.Selector.(*DeleteRequest_Filter); ok {
			return x.Filter
		}
	}
	return nil
}

type isDeleteRequest_Selector interface {
	isDeleteRequest_Selector()
}

type DeleteRequest_Id struct {
	Id string `protobuf:"bytes,2,opt,name=id,proto3,oneof"` // Delete by ID
}

type DeleteRequest_Filter struct {
	Filter *Filter `protobuf:"bytes,3,opt,name=filter,proto3,oneof"` // Delete by filter
}

func (*DeleteRequest_Id) isDeleteRequest_Selector() {}

func (*DeleteRequest_Filter) isDeleteRequest_Selector() {}

// DeleteResponse confirms deletion
type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedCount  int32                  `protobuf:"varint,1,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"` // Number of vectors deleted
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`                               // Operation success status
	Error         *string                `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`                              // Error message if failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_proto_vector_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteResponse) GetDeletedCount() int32 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

// UpdateRequest updates a vector
type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`                                                                         // Namespace
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`                                                                                       // Vector ID to update
	Vector        []float32              `protobuf:"fixed32,3,rep,packed,name=vector,proto3" json:"vector,omitempty"`                                                                      // New vector (if updating vector, empty if not)
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // New metadata (if updating metadata, empty if not)
	Text          *string                `protobuf:"bytes,5,opt,name=text,proto3,oneof" json:"text,omitempty"`                                                                             // New text content
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_proto_vector_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *UpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRequest) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *UpdateRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UpdateRequest) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

// UpdateResponse confirms update
type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`  // Operation success status
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"` // Error message if failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_proto_vector_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

// BatchInsertResponse summarizes batch insertion
type BatchInsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InsertedCount int32                  `protobuf:"varint,1,opt,name=inserted_count,json=insertedCount,proto3" json:"inserted_count,omitempty"` // Number of vectors inserted
	FailedCount   int32                  `protobuf:"varint,2,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`       // Number of failed insertions
	InsertedIds   []string               `protobuf:"bytes,3,rep,name=inserted_ids,json=insertedIds,proto3" json:"inserted_ids,omitempty"`        // IDs of inserted vectors
	Errors        []string               `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`                                     // Error messages for failed insertions
	TotalTimeMs   float32                `protobuf:"fixed32,5,opt,name=total_time_ms,json=totalTimeMs,proto3" json:"total_time_ms,omitempty"`    // Total time in milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchInsertResponse) Reset() {
	*x = BatchInsertResponse{}
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchInsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchInsertResponse) ProtoMessage() {}

func (x *BatchInsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchInsertResponse.ProtoReflect.Descriptor instead.
func (*BatchInsertResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_proto_vector_proto_rawDescGZIP(), []int{11}
}

func (x *BatchInsertResponse) GetInsertedCount() int32 {
	if x != nil {
		return x.InsertedCount
	}
	return 0
}

func (x *BatchInsertResponse) GetFailedCount() int32 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

func (x *BatchInsertResponse) GetInsertedIds() []string {
	if x != nil {
		return x.InsertedIds
	}
	return nil
}

func (x *BatchInsertResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *BatchInsertResponse) GetTotalTimeMs() float32 {
	if x != nil {
		return x.TotalTimeMs
	}
	return 0
}

// Filter represents metadata filtering options
type Filter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to FilterType:
	//
	//	*Filter_Comparison
	//	*Filter_Range
	//	*Filter_List
	//	*Filter_GeoRadius
	//	*Filter_Exists
	//	*Filter_Composite
	FilterType    isFilter_FilterType `protobuf_oneof:"filter_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_proto_vector_proto_rawDescGZIP(), []int{12}
}

func (x *Filter) GetFilterType() isFilter_FilterType {
	if x != nil {
		return x.FilterType
	}
	return nil
}

func (x *Filter) GetComparison() *ComparisonFilter {
	if x != nil {
		if x, ok := x.FilterType.(*Filter_Comparison); ok {
			return x.Comparison
		}
	}
	return nil
}

func (x *Filter) GetRange() *RangeFilter {
	if x != nil {
		if x, ok := x.FilterType.(*Filter_Range); ok {
			return x.Range
		}
	}
	return nil
}

func (x *Filter) GetList() *ListFilter {
	if x != nil {
		if x, ok := x.FilterType.(*Filter_List); ok {
			return x.List
		}
	}
	return nil
}

func (x *Filter) GetGeoRadius() *GeoRadiusFilter {
	if x != nil {
		if x, ok := x.FilterType.(*Filter_GeoRadius); ok {
			return x.GeoRadius
		}
	}
	return nil
}

func (x *Filter) GetExists() *ExistsFilter {
	if x != nil {
		if x, ok := x.FilterType.(*Filter_Exists); ok {
			return x.Exists
		}
	}
	return nil
}

func (x *Filter) GetComposite() *CompositeFilter {
	if x != nil {
		if x, ok := x.FilterType.(*Filter_Composite); ok {
			return x.Composite
		}
	}
	return nil
}

type isFilter_FilterType interface {
	isFilter_FilterType()
}

type Filter_Comparison struct {
	Comparison *ComparisonFilter `protobuf:"bytes,1,opt,name=comparison,proto3,oneof"`
}

type Filter_Range struct {
	Range *RangeFilter `protobuf:"bytes,2,opt,name=range,proto3,oneof"`
}

type Filter_List struct {
	List *ListFilter `protobuf:"bytes,3,opt,name=list,proto3,oneof"`
}

type Filter_GeoRadius struct {
	GeoRadius *GeoRadiusFilter `protobuf:"bytes,4,opt,name=geo_radius,json=geoRadius,proto3,oneof"`
}

type Filter_Exists struct {
	Exists *ExistsFilter `protobuf:"bytes,5,opt,name=exists,proto3,oneof"`
}

type Filter_Composite struct {
	Composite *CompositeFilter `protobuf:"bytes,6,opt,name=composite,proto3,oneof"`
}

func (*Filter_Comparison) isFilter_FilterType() {}

func (*Filter_Range) isFilter_FilterType() {}

func (*Filter_List) isFilter_FilterType() {}

func (*Filter_GeoRadius) isFilter_FilterType() {}

func (*Filter_Exists) isFilter_FilterType() {}

func (*Filter_Composite) isFilter_FilterType() {}

// ComparisonFilter for equality/inequality checks
type ComparisonFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`       // Field name
	Operator      string                 `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"` // "eq", "ne", "gt", "lt", "gte", "lte"
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`       // Value to compare (string representation)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComparisonFilter) Reset() {
	*x = ComparisonFilter{}
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComparisonFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComparisonFilter) ProtoMessage() {}

func (x *ComparisonFilter) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComparisonFilter.ProtoReflect.Descriptor instead.
func (*ComparisonFilter) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_proto_vector_proto_rawDescGZIP(), []int{13}
}

func (x *ComparisonFilter) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ComparisonFilter) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *ComparisonFilter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// RangeFilter for numeric ranges
type RangeFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`   // Field name
	Gte           *string                `protobuf:"bytes,2,opt,name=gte,proto3,oneof" json:"gte,omitempty"` // Greater than or equal
	Lte           *string                `protobuf:"bytes,3,opt,name=lte,proto3,oneof" json:"lte,omitempty"` // Less than or equal
	Gt            *string                `protobuf:"bytes,4,opt,name=gt,proto3,oneof" json:"gt,omitempty"`   // Greater than
	Lt            *string                `protobuf:"bytes,5,opt,name=lt,proto3,oneof" json:"lt,omitempty"`   // Less than
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeFilter) Reset() {
	*x = RangeFilter{}
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeFilter) ProtoMessage() {}

func (x *RangeFilter) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeFilter.ProtoReflect.Descriptor instead.
func (*RangeFilter) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_proto_vector_proto_rawDescGZIP(), []int{14}
}

func (x *RangeFilter) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *RangeFilter) GetGte() string {
	if x != nil && x.Gte != nil {
		return *x.Gte
	}
	return ""
}

func (x *RangeFilter) GetLte() string {
	if x != nil && x.Lte != nil {
		return *x.Lte
	}
	return ""
}

func (x *RangeFilter) GetGt() string {
	if x != nil && x.Gt != nil {
		return *x.Gt
	}
	return ""
}

func (x *RangeFilter) GetLt() string {
	if x != nil && x.Lt != nil {
		return *x.Lt
	}
	return ""
}

// ListFilter for IN/NOT IN operations
type ListFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`       // Field name
	Operator      string                 `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"` // "in" or "not_in"
	Values        []string               `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`     // List of values
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilter) Reset() {
	*x = ListFilter{}
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilter) ProtoMessage() {}

func (x *ListFilter) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilter.ProtoReflect.Descriptor instead.
func (*ListFilter) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_proto_vector_proto_rawDescGZIP(), []int{15}
}

func (x *ListFilter) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ListFilter) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *ListFilter) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// GeoRadiusFilter for geographic radius queries
type GeoRadiusFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`                         // Field name (should contain geo coordinates)
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`                 // Center latitude
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`               // Center longitude
	RadiusKm      float64                `protobuf:"fixed64,4,opt,name=radius_km,json=radiusKm,proto3" json:"radius_km,omitempty"` // Radius in kilometers
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoRadiusFilter) Reset() {
	*x = GeoRadiusFilter{}
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoRadiusFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoRadiusFilter) ProtoMessage() {}

func (x *GeoRadiusFilter) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoRadiusFilter.ProtoReflect.Descriptor instead.
func (*GeoRadiusFilter) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_proto_vector_proto_rawDescGZIP(), []int{16}
}

func (x *GeoRadiusFilter) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *GeoRadiusFilter) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GeoRadiusFilter) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GeoRadiusFilter) GetRadiusKm() float64 {
	if x != nil {
		return x.RadiusKm
	}
	return 0
}

// ExistsFilter checks field existence
type ExistsFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`    // Field name
	Exists        bool                   `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"` // true to check existence, false for non-existence
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistsFilter) Reset() {
	*x = ExistsFilter{}
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistsFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsFilter) ProtoMessage() {}

func (x *ExistsFilter) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsFilter.ProtoReflect.Descriptor instead.
func (*ExistsFilter) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_proto_vector_proto_rawDescGZIP(), []int{17}
}

func (x *ExistsFilter) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ExistsFilter) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

// CompositeFilter combines multiple filters
type CompositeFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operator      string                 `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"` // "and", "or", "not"
	Filters       []*Filter              `protobuf:"bytes,2,rep,name=filters,proto3" json:"filters,omitempty"`   // Sub-filters
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompositeFilter) Reset() {
	*x = CompositeFilter{}
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompositeFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompositeFilter) ProtoMessage() {}

func (x *CompositeFilter) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompositeFilter.ProtoReflect.Descriptor instead.
func (*CompositeFilter) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_proto_vector_proto_rawDescGZIP(), []int{18}
}

func (x *CompositeFilter) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *CompositeFilter) GetFilters() []*Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

// StatsRequest requests database statistics
type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     *string                `protobuf:"bytes,1,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"` // Optional namespace (all if not specified)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_proto_vector_proto_rawDescGZIP(), []int{19}
}

func (x *StatsRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

// StatsResponse returns database statistics
type StatsResponse struct {
	state            protoimpl.MessageState     `protogen:"open.v1"`
	TotalVectors     int64                      `protobuf:"varint,1,opt,name=total_vectors,json=totalVectors,proto3" json:"total_vectors,omitempty"`                                                                                // Total number of vectors
	TotalNamespaces  int64                      `protobuf:"varint,2,opt,name=total_namespaces,json=totalNamespaces,proto3" json:"total_namespaces,omitempty"`                                                                       // Total number of namespaces
	MemoryUsageBytes int64                      `protobuf:"varint,3,opt,name=memory_usage_bytes,json=memoryUsageBytes,proto3" json:"memory_usage_bytes,omitempty"`                                                                  // Approximate memory usage
	NamespaceStats   map[string]*NamespaceStats `protobuf:"bytes,4,rep,name=namespace_stats,json=namespaceStats,proto3" json:"namespace_stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Per-namespace statistics
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_proto_vector_proto_rawDescGZIP(), []int{20}
}

func (x *StatsResponse) GetTotalVectors() int64 {
	if x != nil {
		return x.TotalVectors
	}
	return 0
}

func (x *StatsResponse) GetTotalNamespaces() int64 {
	if x != nil {
		return x.TotalNamespaces
	}
	return 0
}

func (x *StatsResponse) GetMemoryUsageBytes() int64 {
	if x != nil {
		return x.MemoryUsageBytes
	}
	return 0
}

func (x *StatsResponse) GetNamespaceStats() map[string]*NamespaceStats {
	if x != nil {
		return x.NamespaceStats
	}
	return nil
}

// NamespaceStats contains statistics for a single namespace
type NamespaceStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VectorCount   int64                  `protobuf:"varint,1,opt,name=vector_count,json=vectorCount,proto3" json:"vector_count,omitempty"` // Number of vectors in namespace
	MemoryBytes   int64                  `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"` // Memory usage for namespace
	Dimensions    int32                  `protobuf:"varint,3,opt,name=dimensions,proto3" json:"dimensions,omitempty"`                      // Vector dimensions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespaceStats) Reset() {
	*x = NamespaceStats{}
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceStats) ProtoMessage() {}

func (x *NamespaceStats) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceStats.ProtoReflect.Descriptor instead.
func (*NamespaceStats) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_proto_vector_proto_rawDescGZIP(), []int{21}
}

func (x *NamespaceStats) GetVectorCount() int64 {
	if x != nil {
		return x.VectorCount
	}
	return 0
}

func (x *NamespaceStats) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *NamespaceStats) GetDimensions() int32 {
	if x != nil {
		return x.Dimensions
	}
	return 0
}

// HealthCheckRequest requests health status
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_proto_vector_proto_rawDescGZIP(), []int{22}
}

// HealthCheckResponse returns health status
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                                                                             // "healthy", "degraded", or "unhealthy"
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`                                                                           // Server version
	UptimeSeconds int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`                                         // Server uptime
	Details       map[string]string      `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional health details
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_proto_vector_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_proto_vector_proto_rawDescGZIP(), []int{23}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HealthCheckResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_pkg_api_grpc_proto_vector_proto protoreflect.FileDescriptor

const file_pkg_api_grpc_proto_vector_proto_rawDesc = "" +
	"\n" +
	"\x1fpkg/api/grpc/proto/vector.proto\x12\x06vector\"\x81\x02\n" +
	"\rInsertRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x16\n" +
	"\x06vector\x18\x02 \x03(\x02R\x06vector\x12?\n" +
	"\bmetadata\x18\x03 \x03(\v2#.vector.InsertRequest.MetadataEntryR\bmetadata\x12\x13\n" +
	"\x02id\x18\x04 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x17\n" +
	"\x04text\x18\x05 \x01(\tH\x01R\x04text\x88\x01\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x05\n" +
	"\x03_idB\a\n" +
	"\x05_text\"_\n" +
	"\x0eInsertResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x19\n" +
	"\x05error\x18\x03 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\xf5\x01\n" +
	"\rSearchRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12!\n" +
	"\fquery_vector\x18\x02 \x03(\x02R\vqueryVector\x12\f\n" +
	"\x01k\x18\x03 \x01(\x05R\x01k\x12\x1b\n" +
	"\tef_search\x18\x04 \x01(\x05R\befSearch\x12+\n" +
	"\x06filter\x18\x05 \x01(\v2\x0e.vector.FilterH\x00R\x06filter\x88\x01\x01\x12,\n" +
	"\x0fdistance_metric\x18\x06 \x01(\tH\x01R\x0edistanceMetric\x88\x01\x01B\t\n" +
	"\a_filterB\x12\n" +
	"\x10_distance_metric\"\x9c\x02\n" +
	"\x13HybridSearchRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12!\n" +
	"\fquery_vector\x18\x02 \x03(\x02R\vqueryVector\x12\x1d\n" +
	"\n" +
	"query_text\x18\x03 \x01(\tR\tqueryText\x12\f\n" +
	"\x01k\x18\x04 \x01(\x05R\x01k\x12\x1b\n" +
	"\tef_search\x18\x05 \x01(\x05R\befSearch\x12+\n" +
	"\x06filter\x18\x06 \x01(\v2\x0e.vector.FilterH\x00R\x06filter\x88\x01\x01\x127\n" +
	"\x06config\x18\a \x01(\v2\x1a.vector.HybridSearchConfigH\x01R\x06config\x88\x01\x01B\t\n" +
	"\a_filterB\t\n" +
	"\a_config\"\x94\x01\n" +
	"\x12HybridSearchConfig\x12#\n" +
	"\rfusion_method\x18\x01 \x01(\tR\ffusionMethod\x12#\n" +
	"\rvector_weight\x18\x02 \x01(\x02R\fvectorWeight\x12\x1f\n" +
	"\vtext_weight\x18\x03 \x01(\x02R\n" +
	"textWeight\x12\x13\n" +
	"\x05rrf_k\x18\x04 \x01(\x05R\x04rrfK\"\xb0\x01\n" +
	"\x0eSearchResponse\x12.\n" +
	"\aresults\x18\x01 \x03(\v2\x14.vector.SearchResultR\aresults\x12#\n" +
	"\rtotal_results\x18\x02 \x01(\x05R\ftotalResults\x12$\n" +
	"\x0esearch_time_ms\x18\x03 \x01(\x02R\fsearchTimeMs\x12\x19\n" +
	"\x05error\x18\x04 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\xdd\x02\n" +
	"\fSearchResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bdistance\x18\x02 \x01(\x02R\bdistance\x12\x16\n" +
	"\x06vector\x18\x03 \x03(\x02R\x06vector\x12>\n" +
	"\bmetadata\x18\x04 \x03(\v2\".vector.SearchResult.MetadataEntryR\bmetadata\x12\x17\n" +
	"\x04text\x18\x05 \x01(\tH\x00R\x04text\x88\x01\x01\x12&\n" +
	"\fvector_score\x18\x06 \x01(\x02H\x01R\vvectorScore\x88\x01\x01\x12\"\n" +
	"\n" +
	"text_score\x18\a \x01(\x02H\x02R\ttextScore\x88\x01\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\a\n" +
	"\x05_textB\x0f\n" +
	"\r_vector_scoreB\r\n" +
	"\v_text_score\"u\n" +
	"\rDeleteRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x02id\x18\x02 \x01(\tH\x00R\x02id\x12(\n" +
	"\x06filter\x18\x03 \x01(\v2\x0e.vector.FilterH\x00R\x06filterB\n" +
	"\n" +
	"\bselector\"t\n" +
	"\x0eDeleteResponse\x12#\n" +
	"\rdeleted_count\x18\x01 \x01(\x05R\fdeletedCount\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x19\n" +
	"\x05error\x18\x03 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\xf5\x01\n" +
	"\rUpdateRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x16\n" +
	"\x06vector\x18\x03 \x03(\x02R\x06vector\x12?\n" +
	"\bmetadata\x18\x04 \x03(\v2#.vector.UpdateRequest.MetadataEntryR\bmetadata\x12\x17\n" +
	"\x04text\x18\x05 \x01(\tH\x00R\x04text\x88\x01\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\a\n" +
	"\x05_text\"O\n" +
	"\x0eUpdateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\xbe\x01\n" +
	"\x13BatchInsertResponse\x12%\n" +
	"\x0einserted_count\x18\x01 \x01(\x05R\rinsertedCount\x12!\n" +
	"\ffailed_count\x18\x02 \x01(\x05R\vfailedCount\x12!\n" +
	"\finserted_ids\x18\x03 \x03(\tR\vinsertedIds\x12\x16\n" +
	"\x06errors\x18\x04 \x03(\tR\x06errors\x12\"\n" +
	"\rtotal_time_ms\x18\x05 \x01(\x02R\vtotalTimeMs\"\xcd\x02\n" +
	"\x06Filter\x12:\n" +
	"\n" +
	"comparison\x18\x01 \x01(\v2\x18.vector.ComparisonFilterH\x00R\n" +
	"comparison\x12+\n" +
	"\x05range\x18\x02 \x01(\v2\x13.vector.RangeFilterH\x00R\x05range\x12(\n" +
	"\x04list\x18\x03 \x01(\v2\x12.vector.ListFilterH\x00R\x04list\x128\n" +
	"\n" +
	"geo_radius\x18\x04 \x01(\v2\x17.vector.GeoRadiusFilterH\x00R\tgeoRadius\x12.\n" +
	"\x06exists\x18\x05 \x01(\v2\x14.vector.ExistsFilterH\x00R\x06exists\x127\n" +
	"\tcomposite\x18\x06 \x01(\v2\x17.vector.CompositeFilterH\x00R\tcompositeB\r\n" +
	"\vfilter_type\"Z\n" +
	"\x10ComparisonFilter\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x1a\n" +
	"\boperator\x18\x02 \x01(\tR\boperator\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"\x99\x01\n" +
	"\vRangeFilter\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x15\n" +
	"\x03gte\x18\x02 \x01(\tH\x00R\x03gte\x88\x01\x01\x12\x15\n" +
	"\x03lte\x18\x03 \x01(\tH\x01R\x03lte\x88\x01\x01\x12\x13\n" +
	"\x02gt\x18\x04 \x01(\tH\x02R\x02gt\x88\x01\x01\x12\x13\n" +
	"\x02lt\x18\x05 \x01(\tH\x03R\x02lt\x88\x01\x01B\x06\n" +
	"\x04_gteB\x06\n" +
	"\x04_lteB\x05\n" +
	"\x03_gtB\x05\n" +
	"\x03_lt\"V\n" +
	"\n" +
	"ListFilter\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x1a\n" +
	"\boperator\x18\x02 \x01(\tR\boperator\x12\x16\n" +
	"\x06values\x18\x03 \x03(\tR\x06values\"~\n" +
	"\x0fGeoRadiusFilter\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x1b\n" +
	"\tradius_km\x18\x04 \x01(\x01R\bradiusKm\"<\n" +
	"\fExistsFilter\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x16\n" +
	"\x06exists\x18\x02 \x01(\bR\x06exists\"W\n" +
	"\x0fCompositeFilter\x12\x1a\n" +
	"\boperator\x18\x01 \x01(\tR\boperator\x12(\n" +
	"\afilters\x18\x02 \x03(\v2\x0e.vector.FilterR\afilters\"?\n" +
	"\fStatsRequest\x12!\n" +
	"\tnamespace\x18\x01 \x01(\tH\x00R\tnamespace\x88\x01\x01B\f\n" +
	"\n" +
	"_namespace\"\xbc\x02\n" +
	"\rStatsResponse\x12#\n" +
	"\rtotal_vectors\x18\x01 \x01(\x03R\ftotalVectors\x12)\n" +
	"\x10total_namespaces\x18\x02 \x01(\x03R\x0ftotalNamespaces\x12,\n" +
	"\x12memory_usage_bytes\x18\x03 \x01(\x03R\x10memoryUsageBytes\x12R\n" +
	"\x0fnamespace_stats\x18\x04 \x03(\v2).vector.StatsResponse.NamespaceStatsEntryR\x0enamespaceStats\x1aY\n" +
	"\x13NamespaceStatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.vector.NamespaceStatsR\x05value:\x028\x01\"v\n" +
	"\x0eNamespaceStats\x12!\n" +
	"\fvector_count\x18\x01 \x01(\x03R\vvectorCount\x12!\n" +
	"\fmemory_bytes\x18\x02 \x01(\x03R\vmemoryBytes\x12\x1e\n" +
	"\n" +
	"dimensions\x18\x03 \x01(\x05R\n" +
	"dimensions\"\x14\n" +
	"\x12HealthCheckRequest\"\xee\x01\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\x12B\n" +
	"\adetails\x18\x04 \x03(\v2(.vector.HealthCheckResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xf9\x03\n" +
	"\bVectorDB\x127\n" +
	"\x06Insert\x12\x15.vector.InsertRequest\x1a\x16.vector.InsertResponse\x127\n" +
	"\x06Search\x12\x15.vector.SearchRequest\x1a\x16.vector.SearchResponse\x12C\n" +
	"\fHybridSearch\x12\x1b.vector.HybridSearchRequest\x1a\x16.vector.SearchResponse\x127\n" +
	"\x06Delete\x12\x15.vector.DeleteRequest\x1a\x16.vector.DeleteResponse\x127\n" +
	"\x06Update\x12\x15.vector.UpdateRequest\x1a\x16.vector.UpdateResponse\x12C\n" +
	"\vBatchInsert\x12\x15.vector.InsertRequest\x1a\x1b.vector.BatchInsertResponse(\x01\x127\n" +
	"\bGetStats\x12\x14.vector.StatsRequest\x1a\x15.vector.StatsResponse\x12F\n" +
	"\vHealthCheck\x12\x1a.vector.HealthCheckRequest\x1a\x1b.vector.HealthCheckResponseB@Z>github.com/therealutkarshpriyadarshi/vector/pkg/api/grpc/protob\x06proto3"

var (
	file_pkg_api_grpc_proto_vector_proto_rawDescOnce sync.Once
	file_pkg_api_grpc_proto_vector_proto_rawDescData []byte
)

func file_pkg_api_grpc_proto_vector_proto_rawDescGZIP() []byte {
	file_pkg_api_grpc_proto_vector_proto_rawDescOnce.Do(func() {
		file_pkg_api_grpc_proto_vector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_grpc_proto_vector_proto_rawDesc), len(file_pkg_api_grpc_proto_vector_proto_rawDesc)))
	})
	return file_pkg_api_grpc_proto_vector_proto_rawDescData
}

var file_pkg_api_grpc_proto_vector_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_pkg_api_grpc_proto_vector_proto_goTypes = []any{
	(*InsertRequest)(nil),       // 0: vector.InsertRequest
	(*InsertResponse)(nil),      // 1: vector.InsertResponse
	(*SearchRequest)(nil),       // 2: vector.SearchRequest
	(*HybridSearchRequest)(nil), // 3: vector.HybridSearchRequest
	(*HybridSearchConfig)(nil),  // 4: vector.HybridSearchConfig
	(*SearchResponse)(nil),      // 5: vector.SearchResponse
	(*SearchResult)(nil),        // 6: vector.SearchResult
	(*DeleteRequest)(nil),       // 7: vector.DeleteRequest
	(*DeleteResponse)(nil),      // 8: vector.DeleteResponse
	(*UpdateRequest)(nil),       // 9: vector.UpdateRequest
	(*UpdateResponse)(nil),      // 10: vector.UpdateResponse
	(*BatchInsertResponse)(nil), // 11: vector.BatchInsertResponse
	(*Filter)(nil),              // 12: vector.Filter
	(*ComparisonFilter)(nil),    // 13: vector.ComparisonFilter
	(*RangeFilter)(nil),         // 14: vector.RangeFilter
	(*ListFilter)(nil),          // 15: vector.ListFilter
	(*GeoRadiusFilter)(nil),     // 16: vector.GeoRadiusFilter
	(*ExistsFilter)(nil),        // 17: vector.ExistsFilter
	(*CompositeFilter)(nil),     // 18: vector.CompositeFilter
	(*StatsRequest)(nil),        // 19: vector.StatsRequest
	(*StatsResponse)(nil),       // 20: vector.StatsResponse
	(*NamespaceStats)(nil),      // 21: vector.NamespaceStats
	(*HealthCheckRequest)(nil),  // 22: vector.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 23: vector.HealthCheckResponse
	nil,                         // 24: vector.InsertRequest.MetadataEntry
	nil,                         // 25: vector.SearchResult.MetadataEntry
	nil,                         // 26: vector.UpdateRequest.MetadataEntry
	nil,                         // 27: vector.StatsResponse.NamespaceStatsEntry
	nil,                         // 28: vector.HealthCheckResponse.DetailsEntry
}
var file_pkg_api_grpc_proto_vector_proto_depIdxs = []int32{
	24, // 0: vector.InsertRequest.metadata:type_name -> vector.InsertRequest.MetadataEntry
	12, // 1: vector.SearchRequest.filter:type_name -> vector.Filter
	12, // 2: vector.HybridSearchRequest.filter:type_name -> vector.Filter
	4,  // 3: vector.HybridSearchRequest.config:type_name -> vector.HybridSearchConfig
	6,  // 4: vector.SearchResponse.results:type_name -> vector.SearchResult
	25, // 5: vector.SearchResult.metadata:type_name -> vector.SearchResult.MetadataEntry
	12, // 6: vector.DeleteRequest.filter:type_name -> vector.Filter
	26, // 7: vector.UpdateRequest.metadata:type_name -> vector.UpdateRequest.MetadataEntry
	13, // 8: vector.Filter.comparison:type_name -> vector.ComparisonFilter
	14, // 9: vector.Filter.range:type_name -> vector.RangeFilter
	15, // 10: vector.Filter.list:type_name -> vector.ListFilter
	16, // 11: vector.Filter.geo_radius:type_name -> vector.GeoRadiusFilter
	17, // 12: vector.Filter.exists:type_name -> vector.ExistsFilter
	18, // 13: vector.Filter.composite:type_name -> vector.CompositeFilter
	12, // 14: vector.CompositeFilter.filters:type_name -> vector.Filter
	27, // 15: vector.StatsResponse.namespace_stats:type_name -> vector.StatsResponse.NamespaceStatsEntry
	28, // 16: vector.HealthCheckResponse.details:type_name -> vector.HealthCheckResponse.DetailsEntry
	21, // 17: vector.StatsResponse.NamespaceStatsEntry.value:type_name -> vector.NamespaceStats
	0,  // 18: vector.VectorDB.Insert:input_type -> vector.InsertRequest
	2,  // 19: vector.VectorDB.Search:input_type -> vector.SearchRequest
	3,  // 20: vector.VectorDB.HybridSearch:input_type -> vector.HybridSearchRequest
	7,  // 21: vector.VectorDB.Delete:input_type -> vector.DeleteRequest
	9,  // 22: vector.VectorDB.Update:input_type -> vector.UpdateRequest
	0,  // 23: vector.VectorDB.BatchInsert:input_type -> vector.InsertRequest
	19, // 24: vector.VectorDB.GetStats:input_type -> vector.StatsRequest
	22, // 25: vector.VectorDB.HealthCheck:input_type -> vector.HealthCheckRequest
	1,  // 26: vector.VectorDB.Insert:output_type -> vector.InsertResponse
	5,  // 27: vector.VectorDB.Search:output_type -> vector.SearchResponse
	5,  // 28: vector.VectorDB.HybridSearch:output_type -> vector.SearchResponse
	8,  // 29: vector.VectorDB.Delete:output_type -> vector.DeleteResponse
	10, // 30: vector.VectorDB.Update:output_type -> vector.UpdateResponse
	11, // 31: vector.VectorDB.BatchInsert:output_type -> vector.BatchInsertResponse
	20, // 32: vector.VectorDB.GetStats:output_type -> vector.StatsResponse
	23, // 33: vector.VectorDB.HealthCheck:output_type -> vector.HealthCheckResponse
	26, // [26:34] is the sub-list for method output_type
	18, // [18:26] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_pkg_api_grpc_proto_vector_proto_init() }
func file_pkg_api_grpc_proto_vector_proto_init() {
	if File_pkg_api_grpc_proto_vector_proto != nil {
		return
	}
	file_pkg_api_grpc_proto_vector_proto_msgTypes[0].OneofWrappers = []any{}
	file_pkg_api_grpc_proto_vector_proto_msgTypes[1].OneofWrappers = []any{}
	file_pkg_api_grpc_proto_vector_proto_msgTypes[2].OneofWrappers = []any{}
	file_pkg_api_grpc_proto_vector_proto_msgTypes[3].OneofWrappers = []any{}
	file_pkg_api_grpc_proto_vector_proto_msgTypes[5].OneofWrappers = []any{}
	file_pkg_api_grpc_proto_vector_proto_msgTypes[6].OneofWrappers = []any{}
	file_pkg_api_grpc_proto_vector_proto_msgTypes[7].OneofWrappers = []any{
		(*DeleteRequest_Id)(nil),
		(*DeleteRequest_Filter)(nil),
	}
	file_pkg_api_grpc_proto_vector_proto_msgTypes[8].OneofWrappers = []any{}
	file_pkg_api_grpc_proto_vector_proto_msgTypes[9].OneofWrappers = []any{}
	file_pkg_api_grpc_proto_vector_proto_msgTypes[10].OneofWrappers = []any{}
	file_pkg_api_grpc_proto_vector_proto_msgTypes[12].OneofWrappers = []any{
		(*Filter_Comparison)(nil),
		(*Filter_Range)(nil),
		(*Filter_List)(nil),
		(*Filter_GeoRadius)(nil),
		(*Filter_Exists)(nil),
		(*Filter_Composite)(nil),
	}
	file_pkg_api_grpc_proto_vector_proto_msgTypes[14].OneofWrappers = []any{}
	file_pkg_api_grpc_proto_vector_proto_msgTypes[19].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_grpc_proto_vector_proto_rawDesc), len(file_pkg_api_grpc_proto_vector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_grpc_proto_vector_proto_goTypes,
		DependencyIndexes: file_pkg_api_grpc_proto_vector_proto_depIdxs,
		MessageInfos:      file_pkg_api_grpc_proto_vector_proto_msgTypes,
	}.Build()
	File_pkg_api_grpc_proto_vector_proto = out.File
	file_pkg_api_grpc_proto_vector_proto_goTypes = nil
	file_pkg_api_grpc_proto_vector_proto_depIdxs = nil
}
